// src/vue/components/QuotaDialog.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { getInvitationCodeReq, getUserBalanceReq } from '@/api/users'
import closeIcon from '@/assets/images/quota/close.svg'
import topUpIcon from '@/assets/images/quota/top_up.svg'
import exchangeIcon from '@/assets/images/quota/exchange.svg'
import invitationIcon from '@/assets/images/quota/invitation.svg'
//import innerSideIcon from '@/assets/images/quota/inner_side.svg'
import separateWhiteIcon from '@/assets/images/quota/separate_white.svg'
import separateYellowIcon from '@/assets/images/quota/separate_yellow.svg'
import quotaBackImg from '@/assets/images/quota/quota_back.png'
import ExchangeDialog from './ExchangeDialog.vue'
import UsageDetailsDialog from './UsageDetailsDialog.vue'

const model = defineModel<boolean>()

// 额度数据：每日免费 已用/总量万、固定额度万
const dailyFreeUsed = ref(0)  //余额
const dailyFreeTotal = ref(1000000 / 1000) //每日免费固定50万
const fixedQuota = ref(0) // 万 固定额度

// 邀请记录：累计获赠积分万、邀请人数
const bonusPoints = ref(0) // 万
const inviteeCount = ref(0)

// 邀请链接（不可输入，复制用）
const invitationLink = ref('https://baowenmao.com')

// 兑换弹层
const showExchangeDialog = ref(false)
// 使用情况弹层
const showUsageDetailsDialog = ref(false)

const closeDialog = () => {
  model.value = false
}

// 充值：点击提示暂未开放
const handleTopUp = () => {
  ElMessage.info('暂未开放')
}

// 兑换：打开兑换弹层
const handleOpenExchange = () => {
  showExchangeDialog.value = true
}

// 使用情况：打开使用情况弹层
const handleOpenUsageDetails = () => {
  showUsageDetailsDialog.value = true
}

// 使用情况弹层右上角关闭：关闭使用情况 + 额度弹层
const handleCloseAllDialogs = () => {
  showUsageDetailsDialog.value = false
  model.value = false
}

// 复制：把左侧框(不可输入)的内容复制到剪切板
const handleCopyLink = async () => {
  try {
    await navigator.clipboard.writeText(invitationLink.value)
    ElMessage.success('邀请链接已复制到剪贴板')
  } catch {
    const textarea = document.createElement('textarea')
    textarea.value = invitationLink.value
    document.body.appendChild(textarea)
    textarea.select()
    try {
      document.execCommand('copy')
      ElMessage.success('邀请链接已复制到剪贴板')
    } catch {
      ElMessage.error('复制失败，请手动复制')
    }
    document.body.removeChild(textarea)
  }
}

const updateQuota = async () => {
  try {
    const res: any = await getUserBalanceReq()
    if (res?.dailyFreeToken != null && typeof res.dailyFreeToken === 'number' && !isNaN(res.dailyFreeToken)) {
      dailyFreeUsed.value = parseFloat((res.dailyFreeToken / 1000).toFixed(0));
    }
    if (res?.token != null && typeof res.token === 'number' && !isNaN(res.token)) {
      fixedQuota.value = parseFloat((res.token / 1000).toFixed(0))
    }
    // if (res?.bonusPoints != null) bonusPoints.value = res.bonusPoints
    // if (res?.inviteeCount != null) inviteeCount.value = res.inviteeCount
  } catch {
    // 保持默认
  }
}

const updateInvitation = async () => {
  try {
    const res: any = await getInvitationCodeReq()
    // 接口返回数据：{ code, invitationNumber, link, token }
    if (res?.code) {
      // 使用当前域名拼接邀请链接
      invitationLink.value = `${window.location.origin}?invitationCode=${res.code}`
    }
    // 设置邀请人数
    if (res?.invitationNumber != null && typeof res.invitationNumber === 'number' && !isNaN(res.invitationNumber)) {
      inviteeCount.value = res.invitationNumber
    }
    // 设置累计获赠积分（token 除以 10000，参照额度处理方式）
    if (res?.token != null && typeof res.token === 'number' && !isNaN(res.token)) {
      bonusPoints.value = parseFloat((res.token / 1000).toFixed(0))
    }
  } catch {
    // 使用默认链接
  }
}


watch(model, async (newVal) => {
  if (newVal) {
    await updateQuota()
    await updateInvitation()
  }
})
</script>

<template>
  <el-dialog
    :model-value="model"
    :show-close="false"
    :close-on-click-modal="false"
    align-center
    @close="closeDialog" class="quota-dialog"
  >
    <template #header>
      <div class="dialog-header">
        <h2 class="dialog-title">额度</h2>
        <button class="close-btn" aria-label="关闭" @click="closeDialog">
          <img :src="closeIcon" alt="关闭"/>
        </button>
      </div>
    </template>
    <div class="quota-content">
      <!-- 主额度区块：quota_back.png 做背景，内测版右上叠盖且稍靠里 -->
      <div class="quota-main">
        <!-- <div class="beta-badge">
          <div class="beta-badge-content"><img :src="innerSideIcon" alt="" class="beta-icon" />
            <span>内测版</span>
          </div>
        </div> -->
        <img :src="quotaBackImg" alt="" class="quota-back-image" aria-hidden="true"/>
        <div class="position-card"></div>
        <div class="quota-card">
          <div class="quota-left">
            <div class="big-num">
              {{ dailyFreeUsed }}/{{ dailyFreeTotal }}
            </div>
            <div class="sub">（内测每日积分）</div>
          </div>
          <img :src="separateWhiteIcon" alt="" class="sep" aria-hidden="true"/>
          <div class="quota-right">
            <div class="big-num">{{ fixedQuota }}</div>
            <div class="sub">（固定积分）</div>
          </div>
        </div>
        <div class="action-btns">
          <button class="action-btn" @click="handleTopUp">
            <img :src="topUpIcon" alt=""/>
            <span>充值</span>
          </button>
          <img :src="separateYellowIcon" class="sep-y" alt="">
          <button class="action-btn" @click="handleOpenExchange">
            <img :src="exchangeIcon" alt=""/>
            <span>兑换</span>
          </button>
        </div>
      </div>

      <!-- 分割线 -->
      <div class="divider"/>

      <!-- 邀请记录 -->
      <div class="invite-section">
        <div class="invite-title">
          <img :src="invitationIcon" alt="" class="invite-icon"/>
          <span>邀请记录</span>
        </div>
        <div class="invite-card">
          <div class="invite-left">
            <div class="invite-num">{{ bonusPoints }}</div>
            <div class="invite-label">（累计获赠积分）</div>
          </div>
          <img :src="separateYellowIcon" alt="" class="sep-yellow" aria-hidden="true"/>
          <div class="invite-right">
            <div class="invite-num">{{ inviteeCount }}<span class="unit">人</span></div>
            <div class="invite-label">（邀请人数）</div>
          </div>
        </div>
        <div class="share-desc">分享邀请链接，新用户注册每人可获得200积分</div>
        <div class="link-row">
          <input :value="invitationLink" type="text" class="link-input" readonly/>
          <button class="copy-btn" @click="handleCopyLink">复制</button>
        </div>
        <!-- 分隔线 + 使用情况 -->
        <div class="usage-divider"/>
        <div class="usage-row">
          <div class="usage-item" @click="handleOpenUsageDetails">
            <span class="iconfont usage-icon" title="使用情况">&#xe619;</span>
            <span>使用情况</span>
          </div>
        </div>
      </div>
    </div>
  </el-dialog>

  <ExchangeDialog v-model="showExchangeDialog" @success="updateQuota"/>
  <UsageDetailsDialog v-model="showUsageDetailsDialog" @close-all="handleCloseAllDialogs"/>
</template>

<style lang="less">
/* 弹层 teleport 到 body，scoped 无法作用到挂载在 body 的节点，需单独未 scoped 的样式 */

.el-dialog.quota-dialog {
  --el-dialog-width: 722px;
  border-radius: 20px;
  padding: 0;
  overflow: visible;

  .el-dialog__header {
    padding: 35px;
    margin: 0;
  }
}
</style>

<style scoped lang="less">
.dialog-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  width: 100%;
}

.dialog-title {
  margin: 0;
  margin-left: 17px;
  margin-top: 22px;
  font-size: 36px;
  font-weight: 700;
  color: transparent;
  background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
  -webkit-background-clip: text;
  background-clip: text;
  line-height: 1.32;
}

.close-btn {
  flex-shrink: 0;
  width: 22px;
  height: 22px;
  padding: 0;
  border: none;
  background: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;

  img {
    width: 22px;
    height: 22px;
    opacity: 0.8;
  }
}

.quota-content {
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 0 69px;

  .quota-main {
    position: relative;
    margin-top: 9px;
    width: 100%;

    /* 内测版：右上叠盖，稍微靠里 */

    .beta-badge {
      position: absolute;
      top: 4px;
      right: 6px;
      display: flex;
      flex-direction: row;
      justify-content: flex-end;
      align-items: flex-start;
      width: 400px;
      height: 150px;
      padding: 7px 27px;
      border-radius: 10px;
      background: #fff;
      border: 1px solid #ff9500;
      background-clip: padding-box;

      .beta-badge-content {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 7px;
      }

      // &::before {
      //   content: '';
      //   position: absolute;
      //   inset: 0;
      //   border-radius: 10px;
      //   padding: 1px;
      //   background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
      //   -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
      //   mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
      //   -webkit-mask-composite: xor;
      //   mask-composite: exclude;
      //   pointer-events: none;
      // }

      .beta-icon {
        width: 21px;
        height: 21px;
      }

      span {
        font-size: 20px;
        font-weight: 700;
        color: transparent;
        background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
        -webkit-background-clip: text;
        background-clip: text;
      }
    }

    .quota-back-image {
      width: 100%;
      position: absolute;
      left: 0;
      top: 0;
      // height: 186px;
      aspect-ratio: 195/62;
      object-fit: cover;
      z-index: 1;
    }

    .position-card {
      width: 100%;
      aspect-ratio: 195/62;
    }

    .quota-card {
      position: absolute;
      left: 0;
      top: 0;
      width: 100%;
      aspect-ratio: 195/62;
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      z-index: 2;

      .quota-left,
      .quota-right {
        flex: 1;
        margin-top: 15px;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
      }


      .big-num {
        font-size: 40px;
        font-weight: 700;
        color: #fff;
        line-height: 1.32;

        .unit {
          font-size: 20px;
          font-weight: 400;
        }
      }

      .sub {
        font-size: 16px;
        color: rgba(255, 255, 255, 0.8);
        line-height: 1.32;
        margin-top: 10px;
      }

      .sep {
        width: 2px;
        height: 67px;
        flex-shrink: 0;
        margin: 0 24px;
        align-self: center;
      }
    }

    .action-btns {
      display: flex;
      height: 54px;
      width: 100%;
      flex-direction: row;
      border-bottom-left-radius: 20px;
      border-bottom-right-radius: 20px;
      border-bottom: 1px solid #EFAF00;
      border-left: 1px solid #EFAF00;
      border-right: 1px solid #EFAF00;
      justify-content: center;
      align-items: center;

      .sep-y {
        width: 1px;
        height: 39px;
      }

      .action-btn {
        display: flex;
        align-items: center;
        flex-direction: row;
        justify-content: center;
        flex: 1;
        gap: 6px;
        padding: 0;
        border: none;
        background: none;
        font-size: 20px;
        font-weight: 400;
        color: #9a9a9a;
        cursor: pointer;
        line-height: 1.32;

        img {
          width: 21px;
          height: 21px;
        }

        &:last-child img {
          width: 26px;
          height: 24px;
        }
      }
    }
  }

  .divider {
    height: 1px;
    width: 100%;
    background: #dadada;
    opacity: 0.5;
    margin: 33px 0 20px 0;
  }

  .invite-section {
    width: 100%;
    padding-left: 6px;

    .invite-title {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 20px;

      .invite-icon {
        width: 24px;
        height: 26px;
      }

      span {
        font-size: 20px;
        font-weight: 700;
        color: transparent;
        background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
        -webkit-background-clip: text;
        background-clip: text;
      }
    }

    .invite-card {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 20px;
      position: relative;
      height: 122px;
      width: 100%;
      border-radius: 20px;
      border: 1px solid transparent;
      background: linear-gradient(180deg, #fff8e5 0%, #fff 100%);
      background-clip: padding-box;

      &::before {
        content: '';
        position: absolute;
        inset: 0;
        border-radius: 20px;
        padding: 1px;
        background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
        mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
        -webkit-mask-composite: xor;
        mask-composite: exclude;
        pointer-events: none;
      }


      .invite-left,
      .invite-right {
        display: flex;
        flex: 1;
        flex-direction: column;
        align-items: center;
        text-align: center;
      }


      .invite-num {
        font-size: 24px;
        font-weight: 400;
        color: #464646;
        line-height: 1.32;

        .unit {
          font-size: 15px;
        }
      }

      .invite-label {
        font-size: 13px;
        color: #999;
        margin-top: 11px;
        line-height: 1.32;
      }

      .sep-yellow {
        width: 1px;
        height: 48px;
        flex-shrink: 0;
      }
    }

    .share-desc {
      font-size: 14px;
      color: #999;
      line-height: 1.32;
      margin-bottom: 14px;
    }

    .link-row {
      display: flex;
      align-items: center;
      gap: 19px;
      height: 43px;
      margin-bottom: 20px;

      .link-input {
        flex: 1;
        height: 43px;
        padding: 0 13px;
        border: none;
        border-radius: 10px;
        background: #f5f5f5;
        font-size: 16px;
        color: #999;
        outline: none;
        cursor: default;
      }

      .copy-btn {
        flex-shrink: 0;
        width: 68px;
        height: 37px;
        border: none;
        border-radius: 10px;
        background: linear-gradient(90deg, #efaf00 0%, #ff9500 100%);
        font-size: 18px;
        font-weight: 400;
        color: #fff;
        cursor: pointer;
        line-height: 1.32;
      }
    }

    .usage-divider {
      height: 1px;
      width: 100%;
      background: #dadada;
      opacity: 0.5;
      margin: 0 0 20px 0;
    }

    .usage-row {
      display: flex;
      align-items: center;
      gap: 24px;
      margin-bottom: 58px;
    }

    .usage-item {
      display: flex;
      align-items: center;
      gap: 8px;
      cursor: pointer;
      font-size: 16px;
      font-weight: 400;
      color: #9a9a9a;
      line-height: 1.32;

      .usage-icon {
        font-size: 20px;
        color: #9a9a9a;
      }

      &:hover {
        color: #ff9500;

        .usage-icon {
          color: #ff9500;
        }
      }
    }
  }
}
</style>

// src/components/QuotaDialog/QuotaDialog.tsx
import * as React from 'react'
import { useCallback, useEffect, useState, useRef, useMemo } from 'react'
import { Dialog, DialogContent, DialogTitle, VisuallyHidden } from '@/components/ui/Dialog'
import { Iconfont } from '@/components/IconFont'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/Select'
import { getUserBalanceReq, getInvitationCodeReq } from '@/api/users'
import { getOrderHistory, type Order } from '@/api/order'
import { formatLocalTime } from '@/utils/formatLocalTime'
import { toast } from 'sonner'
import { Loader2 } from 'lucide-react'
import {
  aggregateOrdersBySession,
  filterToOrderType,
  formatPoints,
  getDetailText,
  getPointsClass,
} from './utils'

import topUpIcon from '@/assets/images/quota/top_up.svg'
import exchangeIcon from '@/assets/images/quota/exchange.svg'
import invitationIcon from '@/assets/images/quota/invitation.svg'
import separateWhiteIcon from '@/assets/images/quota/separate_white.svg'
import separateYellowIcon from '@/assets/images/quota/separate_yellow.svg'
import quotaBackImg from '@/assets/images/quota/quota_back.png'
import { openDialog } from '@/lib/openDialog'

export interface QuotaDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const USAGE_FILTER_OPTIONS = [
  { id: '0', name: '全部' },
  { id: '1', name: '获取' },
  { id: '2', name: '消耗' },
] as const
const PAGE_SIZE = 20

export const QuotaDialog = ({ open, onOpenChange }: QuotaDialogProps) => {
  const [view, setView] = useState<'quota' | 'usage'>('quota')
  const [dailyFreeUsed, setDailyFreeUsed] = useState(0)
  const [dailyFreeTotal] = useState(1000000 / 1000)
  const [fixedQuota, setFixedQuota] = useState(0)
  const [bonusPoints, setBonusPoints] = useState(0)
  const [inviteeCount, setInviteeCount] = useState(0)
  const [invitationLink, setInvitationLink] = useState('https://baowenmao.com')

  const [usageFilterType, setUsageFilterType] = useState('0')
  const [ordersList, setOrdersList] = useState<Order[]>([])
  const [isLoadingUsage, setIsLoadingUsage] = useState(false)
  const [isLoadingMoreUsage, setIsLoadingMoreUsage] = useState(false)
  const [hasMoreUsage, setHasMoreUsage] = useState(true)
  const usagePageRef = useRef(-1)
  const usageContentRef = useRef<HTMLDivElement>(null)
  const usageScrollTickingRef = useRef(false)

  const updateQuota = useCallback(async () => {
    try {
      const res: any = await getUserBalanceReq()
      if (
        res?.dailyFreeToken != null &&
        typeof res.dailyFreeToken === 'number' &&
        !isNaN(res.dailyFreeToken)
      ) {
        setDailyFreeUsed(parseFloat((res.dailyFreeToken / 1000).toFixed(0)))
      }
      if (res?.token != null && typeof res.token === 'number' && !isNaN(res.token)) {
        setFixedQuota(parseFloat((res.token / 1000).toFixed(0)))
      }
    } catch {
      // keep default
    }
  }, [])

  const updateInvitation = useCallback(async () => {
    try {
      const res: any = await getInvitationCodeReq()
      if (res?.code) {
        setInvitationLink(`${window.location.origin}?invitationCode=${res.code}`)
      }
      if (
        res?.invitationNumber != null &&
        typeof res.invitationNumber === 'number' &&
        !isNaN(res.invitationNumber)
      ) {
        setInviteeCount(res.invitationNumber)
      }
      if (res?.token != null && typeof res.token === 'number' && !isNaN(res.token)) {
        setBonusPoints(parseFloat((res.token / 1000).toFixed(0)))
      }
    } catch {
      // keep default
    }
  }, [])

  useEffect(() => {
    if (open) {
      updateQuota()
      updateInvitation()
    }
  }, [open, updateQuota, updateInvitation])

  const handleTopUp = useCallback(() => {
    toast.info('暂未开放')
  }, [])

  const handleOpenExchange = useCallback(() => {
    toast.info('兑换功能暂未开放')
  }, [])

  const loadMoreUsage = useCallback(async () => {
    if (isLoadingMoreUsage || isLoadingUsage) return
    if (!hasMoreUsage) return
    const nextPage = usagePageRef.current + 1
    if (nextPage === 0) setIsLoadingUsage(true)
    else setIsLoadingMoreUsage(true)
    try {
      const data = await getOrderHistory({
        page: nextPage,
        size: PAGE_SIZE,
        orderType: filterToOrderType(usageFilterType),
      })
      if (!data?.content || !Array.isArray(data.content)) {
        setHasMoreUsage(false)
        return
      }
      const list = data.content
      if (list.length > 0) {
        setOrdersList(prev => aggregateOrdersBySession([...prev, ...list]))
        usagePageRef.current = nextPage
      }
      const noMore =
        list.length < PAGE_SIZE ||
        (data.totalPages != null && nextPage >= data.totalPages - 1)
      if (noMore) setHasMoreUsage(false)
    } catch {
      setHasMoreUsage(false)
    } finally {
      setIsLoadingUsage(false)
      setIsLoadingMoreUsage(false)
    }
  }, [usageFilterType, isLoadingUsage, isLoadingMoreUsage, hasMoreUsage])

  const resetAndLoadUsage = useCallback(async () => {
    setOrdersList([])
    usagePageRef.current = -1
    setHasMoreUsage(true)
    setIsLoadingUsage(true)
    setIsLoadingMoreUsage(false)
    try {
      const data = await getOrderHistory({
        page: 0,
        size: PAGE_SIZE,
        orderType: filterToOrderType(usageFilterType),
      })
      if (!data?.content || !Array.isArray(data.content)) {
        setHasMoreUsage(false)
        return
      }
      setOrdersList(aggregateOrdersBySession(data.content))
      usagePageRef.current = 0
      const noMore =
        data.content.length < PAGE_SIZE ||
        (data.totalPages != null && 0 >= data.totalPages - 1)
      if (noMore) setHasMoreUsage(false)
    } catch {
      setHasMoreUsage(false)
    } finally {
      setIsLoadingUsage(false)
    }
  }, [usageFilterType])

  const handleUsageScroll = useCallback(() => {
    if (usageScrollTickingRef.current) return
    usageScrollTickingRef.current = true
    requestAnimationFrame(() => {
      const el = usageContentRef.current
      if (el) {
        const { scrollTop, scrollHeight, clientHeight } = el
        if (scrollHeight - scrollTop - clientHeight < 50) loadMoreUsage()
      }
      usageScrollTickingRef.current = false
    })
  }, [loadMoreUsage])

  const handleOpenUsageDetails = useCallback(() => {
    setView('usage')
    setOrdersList([])
    usagePageRef.current = -1
    setHasMoreUsage(true)
    setUsageFilterType('0')
  }, [])

  const handleUsageReturn = useCallback(() => {
    setView('quota')
    setOrdersList([])
    usagePageRef.current = -1
  }, [])

  const handleUsageCloseAll = useCallback(() => {
    setView('quota')
    onOpenChange(false)
    setOrdersList([])
    usagePageRef.current = -1
  }, [onOpenChange])

  const handleDialogOpenChange = useCallback(
    (next: boolean) => {
      if (!next) setView('quota')
      onOpenChange(next)
    },
    [onOpenChange]
  )

  const usageRows = useMemo(
    () =>
      ordersList.map((order) => ({
        id: order.id,
        detailText: getDetailText(order),
        createdTimeText: formatLocalTime(order.createdTime),
        pointsText: formatPoints(order),
        pointsClass: getPointsClass(order),
      })),
    [ordersList]
  )

  useEffect(() => {
    if (view === 'usage') {
      void resetAndLoadUsage()
    }
  }, [view, usageFilterType, resetAndLoadUsage])

  const handleCopyLink = useCallback(async () => {
    try {
      const copyText = `我最近在用【爆文猫】AI写作工具，宝藏功能有：AI教练、拆书仿写、切换文风、小说转剧本……\n${invitationLink} \n快帮我点点邀请链接，登录就能薅百万token！`
      await navigator.clipboard.writeText(copyText)
      toast.success('邀请链接已复制到剪贴板')
    } catch {
      const textarea = document.createElement('textarea')
      textarea.value = invitationLink
      document.body.appendChild(textarea)
      textarea.select()
      try {
        document.execCommand('copy')
        toast.success('邀请链接已复制到剪贴板')
      } catch {
        toast.error('复制失败，请手动复制')
      }
      document.body.removeChild(textarea)
    }
  }, [invitationLink])

  const preventClose = useCallback((e: Event) => {
    e.preventDefault()
  }, [])

  return (
    <Dialog open={open} onOpenChange={handleDialogOpenChange}>
      <DialogContent
        showCloseButton
        className="w-[722px] p-0"
        onInteractOutside={preventClose}
        onEscapeKeyDown={preventClose}
      >
        <VisuallyHidden>
          <DialogTitle>{view === 'usage' ? '使用情况' : '额度'}</DialogTitle>
        </VisuallyHidden>
        {view === 'usage' ? (
          <>
            <div className="px-8 pt-8 pb-0">
              <div className="h-17 flex items-center justify-between w-full">
                <div className="flex items-center justify-between">
                  <div
                    role="button"
                    className="flex h-10 w-10 items-center justify-center mr-1.5 p-0 border-none bg-transparent cursor-pointer text-[34px] text-[#8c8c8c] hover:text-[#ff9500]"
                    onClick={handleUsageReturn}
                    onKeyDown={e => e.key === 'Enter' && handleUsageReturn()}
                    aria-label="返回"
                  >
                    <Iconfont unicode="&#xeaa2;" />
                  </div>
                  <h2 className="m-0 flex-1 text-[36px] font-bold leading-[1.32] text-transparent bg-linear-to-r from-[#efaf00] to-[#ff9500] bg-clip-text">
                    使用情况
                  </h2>
                </div>
                <Select value={usageFilterType} onValueChange={setUsageFilterType}>
                  <SelectTrigger className="min-w-[100px] h-[30px] rounded-[20px] border-[#d8d8d8] px-3.5 text-[15px] text-[#8c8c8c]">
                    <SelectValue placeholder="请选择" />
                  </SelectTrigger>
                  <SelectContent align="end">
                    {USAGE_FILTER_OPTIONS.map((opt) => (
                      <SelectItem key={opt.id} value={opt.id} className='cursor-pointer'>
                        {opt.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="min-h-[480px] max-h-[660px] h-[660px] flex flex-col overflow-hidden px-[35px] pt-6 pb-[35px]">
              <div className="flex-1 min-h-0 flex flex-col border border-[#e5e5e5] rounded-[20px] overflow-hidden bg-white">
                <div className="shrink-0 flex items-center px-5 py-3.5 text-[15px] font-semibold text-[#8c8c8c] bg-[#e8e8e8] border-b border-[#e0e0e0]">
                  <div className="flex-1 min-w-0 text-left">详情</div>
                  <div className="w-[200px] shrink-0 text-left">日期</div>
                  <div className="w-[110px] shrink-0 text-left">积分变更</div>
                </div>
                <div
                  ref={usageContentRef}
                  className="flex-1 min-h-0 overflow-y-auto overflow-x-hidden [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar]:w-0 [&::-webkit-scrollbar]:h-0"
                  onScroll={handleUsageScroll}
                  style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
                >
                  {isLoadingUsage && usageRows.length === 0 ? (
                    <div className="flex items-center justify-center gap-2 py-6 text-sm text-[#8c8c8c]">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>加载中...</span>
                    </div>
                  ) : (
                    <>
                      {usageRows.map((row, index) => (
                        <div
                          key={row.id}
                          className={`flex items-center px-5 py-3.5 text-sm text-[#666] border-b border-[#f0f0f0] ${index % 2 === 0 ? 'bg-[#ebebeb]' : 'bg-white'}`}
                        >
                          <div
                            className="flex-1 min-w-0 overflow-hidden text-ellipsis whitespace-nowrap text-left"
                            title={row.detailText}
                          >
                            {row.detailText}
                          </div>
                          <div className="w-[200px] shrink-0 text-left">
                            {row.createdTimeText}
                          </div>
                          <div
                            className={`w-[110px] shrink-0 text-left font-medium ${row.pointsClass}`}
                          >
                            {row.pointsText}
                          </div>
                        </div>
                      ))}
                      {usageRows.length === 0 && (
                        <div className="flex flex-col items-center justify-center py-[60px] px-5 text-[#8c8c8c] text-sm">
                          暂无使用记录
                        </div>
                      )}
                      {isLoadingMoreUsage && (
                        <div className="flex items-center justify-center gap-2 py-6 text-sm text-[#8c8c8c]">
                          <Loader2 className="h-4 w-4 animate-spin" />
                          <span>加载中...</span>
                        </div>
                      )}
                    </>
                  )}
                </div>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="px-8 pt-8 pb-0">
              <h2 className="h-17 px-5 text-[36px] leading-17 text-2xl font-bold text-transparent bg-linear-to-r from-[#efaf00] to-[#ff9500] bg-clip-text">
                额度
              </h2>
            </div>

            <div className="flex flex-col items-center w-full px-[69px] pb-8 h-[660px]">
              <div className="relative mt-[9px] w-full">
                <img
                  src={quotaBackImg}
                  alt=""
                  className="absolute left-0 top-0 w-full z-1 aspect-195/62 object-cover"
                  aria-hidden
                />
                <div className="w-full aspect-195/62" />
                <div className="absolute left-0 top-0 w-full aspect-195/62 flex flex-row items-center justify-center z-2">
                  <div className="flex-1 flex flex-col items-center text-center mt-[15px]">
                    <div className="text-[40px] font-bold text-white leading-[1.32]">
                      {dailyFreeUsed}/{dailyFreeTotal}
                    </div>
                    <div className="text-base text-white/80 leading-[1.32] mt-[10px]">
                      （内测每日积分）
                    </div>
                  </div>
                  <img
                    src={separateWhiteIcon}
                    alt=""
                    className="w-[2px] h-[67px] shrink-0 mx-6 self-center"
                    aria-hidden
                  />
                  <div className="flex-1 flex flex-col items-center text-center mt-[15px]">
                    <div className="text-[40px] font-bold text-white leading-[1.32]">
                      {fixedQuota}
                    </div>
                    <div className="text-base text-white/80 leading-[1.32] mt-[10px]">
                      （固定积分）
                    </div>
                  </div>
                </div>
                <div className="flex h-[54px] w-full flex-row items-center justify-center border-b border-l border-r border-[#EFAF00] rounded-b-[20px]">
                  <div
                    role="button"
                    className="flex flex-1 flex-row items-center justify-center gap-1.5 cursor-pointer text-[20px] font-normal text-[#9a9a9a] leading-[1.32] border-none bg-transparent p-0"
                    onClick={handleTopUp}
                    onKeyDown={e => e.key === 'Enter' && handleTopUp()}
                  >
                    <img src={topUpIcon} alt="" className="h-[21px] w-[21px]" />
                    <span>充值</span>
                  </div>
                  <img src={separateYellowIcon} alt="" className="w-px h-[39px]" />
                  <div
                    role="button"
                    className="flex flex-1 flex-row items-center justify-center gap-1.5 cursor-pointer text-[20px] font-normal text-[#9a9a9a] leading-[1.32] border-none bg-transparent p-0"
                    onClick={handleOpenExchange}
                    onKeyDown={e => e.key === 'Enter' && handleOpenExchange()}
                  >
                    <img src={exchangeIcon} alt="" className="h-[24px] w-[26px]" />
                    <span>兑换</span>
                  </div>
                </div>
              </div>

              <div className="w-full bg-[#dadada] opacity-50 h-px my-5" />

              <div className="w-full pl-1.5">
                <div className="flex items-center gap-4 mb-5">
                  <img src={invitationIcon} alt="" className="h-[26px] w-[24px]" />
                  <span className="text-[20px] font-bold text-transparent bg-linear-to-r from-[#efaf00] to-[#ff9500] bg-clip-text">
                    邀请记录
                  </span>
                </div>
                <div className="flex items-center justify-center mb-5 h-[122px] w-full rounded-[20px] border border-transparent bg-linear-to-b from-[#fff8e5] to-white bg-clip-padding relative">
                  <div className="absolute inset-0 rounded-[20px] p-px bg-linear-to-r from-[#efaf00] to-[#ff9500] mask-exclude [mask:linear-gradient(#fff_0_0)_content-box,linear-gradient(#fff_0_0)]" />
                  <div className="flex-1 flex flex-col items-center text-center">
                    <div className="text-2xl font-normal text-[#464646] leading-[1.32]">
                      {bonusPoints}
                    </div>
                    <div className="text-[13px] text-[#999] mt-[11px] leading-[1.32]">
                      （累计获赠积分）
                    </div>
                  </div>
                  <img src={separateYellowIcon} alt="" className="w-px h-12 shrink-0" aria-hidden />
                  <div className="flex-1 flex flex-col items-center text-center">
                    <div className="text-2xl font-normal text-[#464646] leading-[1.32]">
                      {inviteeCount}
                      <span className="text-[15px]">人</span>
                    </div>
                    <div className="text-[13px] text-[#999] mt-[11px] leading-[1.32]">
                      （邀请人数）
                    </div>
                  </div>
                </div>
                <div className="text-sm text-[#999] leading-[1.32] mb-3.5">
                  分享邀请链接，新用户注册每人可获得200积分
                </div>
                <div className="flex items-center gap-5 h-[43px] mb-5">
                  <input
                    type="text"
                    readOnly
                    value={invitationLink}
                    className="flex-1 h-[43px] px-3 rounded-[10px] border-none bg-[#f5f5f5] text-base text-[#999] outline-none cursor-default"
                  />
                  <div
                    className="shrink-0 w-[68px] h-[37px] flex items-center justify-center rounded-[10px] bg-linear-to-r from-[#efaf00] to-[#ff9500] text-lg font-normal text-white cursor-pointer leading-[1.32] hover:brightness-110 active:brightness-90"
                    onClick={handleCopyLink}
                    onKeyDown={e => e.key === 'Enter' && handleCopyLink()}
                  >
                    复制
                  </div>
                </div>
                <div className="h-px w-full bg-[#dadada] opacity-50 mb-5" />
                <div
                  role="button"
                  className="flex items-center gap-2 cursor-pointer text-base font-normal text-[#9a9a9a] leading-[1.32] hover:text-[#ff9500]"
                  onClick={handleOpenUsageDetails}
                  onKeyDown={e => e.key === 'Enter' && handleOpenUsageDetails()}
                >
                  <span className="iconfont text-xl text-[#9a9a9a] hover:text-[#ff9500]">
                    <Iconfont unicode="&#xe619;" />
                  </span>
                  <span>使用情况</span>
                </div>
              </div>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}

export const openQuotaDialog = () => openDialog(QuotaDialog)
